[phases.setup]
    # https://github.com/NixOS/nixpkgs/commits/master/pkgs/development/web/bun/default.nix
    nixpkgsArchive = 'b81fde59a2e1cb88a516fcec622e00fbe174d3a3' # https://github.com/NixOS/nixpkgs/commit/b81fde59a2e1cb88a516fcec622e00fbe174d3a3 (zig 0.15.2)
